### ISSUE TITLE
能说明下如何设置cookie吗？用的安卓

### ISSUE THREAD

**Issue by better319** [lan-tianxiang/JS_TOOL#26]
用的安卓版本，安装好了，就是要让设置cookie，不知道怎么设置。能给个截图步骤吗？谢谢！

**Comment by Rosylusi** [comment]
一样，然后打不开面板

**Comment by lan-tianxiang** [comment]
> 用的安卓版本，安装好了，就是要让设置cookie，不知道怎么设置。能给个截图步骤吗？谢谢！



> 一样，然后打不开面板


打开面板设置cookie

**Comment by lan-tianxiang** [comment]
手机上有的浏览器打不开127.0.0.1:5678

**Comment by lan-tianxiang** [comment]
> 一样，然后打不开面板

你要先输入`bash jd.sh panelon`打开面包命令
然后输入地址

**Comment by better319** [comment]
![Screenshot_2021-05-27-11-52-55-586_com termux](https://user-images.githubusercontent.com/13842581/119763622-78974d00-bee2-11eb-810d-e01e1c5f60de.jpg)
![Screenshot_2021-05-27-11-53-39-694_com qihoo contents](https://user-images.githubusercontent.com/13842581/119763637-7df49780-bee2-11eb-93e6-e7f6dc898a8e.jpg)


还是有问题？
这个是不是要扫码什么的？还是要装什么app？

**Comment by Rosylusi** [comment]
用的linux deploy应该选安卓还是linux？

**Comment by lan-tianxiang** [comment]
bash jd.sh panelon打开面板

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："better319 ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 中午11:56
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 能说明下如何设置cookie吗？用的安卓 (#26)
-----------------------------------

 

 

 
 
还是有问题？
 这个是不是要扫码什么的？还是要装什么app？

**Comment by Rosylusi** [comment]
大佬，以下这是什么问题？linux_install_jd.sh: line 43: curl: command not found
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
deb https://dl.yarnpkg.com/debian/ stable main
Hit:1 http://mirrors.ustc.edu.cn/debian buster InRelease
Hit:2 http://mirrors.ustc.edu.cn/debian buster-updates InRelease
Hit:3 http://mirrors.ustc.edu.cn/debian-security buster/updates InRelease
Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Err:4 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Reading package lists... Done
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

依赖未安装完整,请重新运行该脚本且切换良好的网络环境！

**Comment by lan-tianxiang** [comment]
curl命令缺失，安装一下curl

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："easonren ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 中午1:02
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 能说明下如何设置cookie吗？用的安卓 (#26)
-----------------------------------

 

 
大佬，以下这是什么问题？linux_install_jd.sh: line 43: curl: command not found
 E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
 deb https://dl.yarnpkg.com/debian/ stable main
 Hit:1 http://mirrors.ustc.edu.cn/debian buster InRelease
 Hit:2 http://mirrors.ustc.edu.cn/debian buster-updates InRelease
 Hit:3 http://mirrors.ustc.edu.cn/debian-security buster/updates InRelease
 Get:4 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
 Err:4 https://dl.yarnpkg.com/debian stable InRelease
 The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
 Reading package lists... Done
 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
 N: Updating from such a repository can't be done securely, and is therefore disabled by default.
 N: See apt-secure(8) manpage for repository creation and user configuration details.
 
依赖未安装完整,请重新运行该脚本且切换良好的网络环境！

**Comment by lan-tianxiang** [comment]
选用linux,不过我推荐还是使用termux部署代码,比较方便，哈哈

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："easonren ***@***.***&gt;;
发送时间：2021年5月27日(星期四) 中午12:09
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 能说明下如何设置cookie吗？用的安卓 (#26)
-----------------------------------

 

 
用的linux deploy应该选安卓还是linux？

**Comment by Rosylusi** [comment]
这又是啥情况啊，老哥？1   debian/ubuntu/armbian/OpenMediaVault，以及其他debian系
Hit:1 http://mirrors.ustc.edu.cn/debian stable InRelease
Hit:2 http://mirrors.ustc.edu.cn/debian stable-updates InRelease       
Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]         
Err:3 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Reading package lists... Done
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

依赖未安装完整,请重新运行该脚本且切换良好的网络环境！

**Comment by lan-tianxiang** [comment]
> 这又是啥情况啊，老哥？1 debian/ubuntu/armbian/OpenMediaVault，以及其他debian系
> Hit:1 http://mirrors.ustc.edu.cn/debian stable InRelease
> Hit:2 http://mirrors.ustc.edu.cn/debian stable-updates InRelease
> Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> Err:3 https://dl.yarnpkg.com/debian stable InRelease
> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> Reading package lists... Done
> W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> 
> 依赖未安装完整,请重新运行该脚本且切换良好的网络环境！

我看一下，稍等

**Comment by lan-tianxiang** [comment]
> ![Screenshot_2021-05-27-11-52-55-586_com termux](https://user-images.githubusercontent.com/13842581/119763622-78974d00-bee2-11eb-810d-e01e1c5f60de.jpg)
> ![Screenshot_2021-05-27-11-53-39-694_com qihoo contents](https://user-images.githubusercontent.com/13842581/119763637-7df49780-bee2-11eb-93e6-e7f6dc898a8e.jpg)
> 
> 还是有问题？
> 这个是不是要扫码什么的？还是要装什么app？


我的问题，已经解决了。
删除软件，重新运行一遍安装脚本，然后在运行`jd panelon`即可 @better319

**Comment by lan-tianxiang** [comment]
> 这又是啥情况啊，老哥？1 debian/ubuntu/armbian/OpenMediaVault，以及其他debian系
> Hit:1 http://mirrors.ustc.edu.cn/debian stable InRelease
> Hit:2 http://mirrors.ustc.edu.cn/debian stable-updates InRelease
> Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> Err:3 https://dl.yarnpkg.com/debian stable InRelease
> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> Reading package lists... Done
> W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> 
> 依赖未安装完整,请重新运行该脚本且切换良好的网络环境！

@895450603  
运行前，输入
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E`
然后再次运行脚本就可以了

**Comment by Rosylusi** [comment]
> > 这又是啥情况啊，老哥？1 debian/ubuntu/armbian/OpenMediaVault，以及其他debian系
> > Hit:1 http://mirrors.ustc.edu.cn/debian stable InRelease
> > Hit:2 http://mirrors.ustc.edu.cn/debian stable-updates InRelease
> > Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> > Err:3 https://dl.yarnpkg.com/debian stable InRelease
> > The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> > Reading package lists... Done
> > W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> > E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
> > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > 依赖未安装完整,请重新运行该脚本且切换良好的网络环境！
> 
> @895450603
> 运行前，输入
> `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E`
> 然后再次运行脚本就可以了

好的，谢谢大佬，手动抱拳

**Comment by lan-tianxiang** [comment]
> > > 这又是啥情况啊，老哥？1 debian/ubuntu/armbian/OpenMediaVault，以及其他debian系
> > > Hit:1 http://mirrors.ustc.edu.cn/debian stable InRelease
> > > Hit:2 http://mirrors.ustc.edu.cn/debian stable-updates InRelease
> > > Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
> > > Err:3 https://dl.yarnpkg.com/debian stable InRelease
> > > The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> > > Reading package lists... Done
> > > W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
> > > E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
> > > N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> > > N: See apt-secure(8) manpage for repository creation and user configuration details.
> > > 依赖未安装完整,请重新运行该脚本且切换良好的网络环境！
> > 
> > 
> > @895450603
> > 运行前，输入
> > `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E`
> > 然后再次运行脚本就可以了
> 
> 好的，谢谢大佬，手动抱拳

没事，不用谢

**Comment by Rosylusi** [comment]
> 
> 
> > > > 这又是啥情况啊，老哥？1 debian/ubuntu/armbian/OpenMediaVault，以及其他debian系 
> > > > 点击数：1 [http://mirrors.ustc.edu.cn/debian ](http://mirrors.ustc.edu.cn/debian)稳定版 
> > > > 点击数：2 [http://mirrors.ustc.edu.cn/debian ](http://mirrors.ustc.edu.cn/debian)stable-updates发布 
> > > > 获取：3 [https://dl.yarnpkg.com/debian ](https://dl.yarnpkg.com/debian)稳定的InRelease [17.1 kB] 
> > > > 错误：3 [https://dl.yarnpkg.com/debian ](https://dl.yarnpkg.com/debian)stable InRelease 
> > > > 由于公共密钥不可用，因此无法验证以下签名：NO_PUBKEY 23E7166788B63E1E 
> > > > 正在阅读包裹清单...完成 
> > > > W：GPG错误： ： [https ](https://dl.yarnpkg.com/debian)//dl.yarnpkg.com/debian稳定InRelease：由于公共密钥不可用，无法验证以下签名：NO_PUBKEY 23E7166788B63E1E 
> > > > E：存储库“ [https://dl.yarnpkg.com/debian ](https://dl.yarnpkg.com/debian)stable InRelease”未签名。 
> > > > N：无法安全地从这样的存储库更新，因此默认情况下被禁用。 
> > > > N：有关存储库创建和用户配置的详细信息，请参见apt-secure（8）联机帮助页。 
> > > > 依赖未安装完整,请重新运行该脚本且切换良好的网络环境！
> > > 
> > > 
> > > @895450603 
> > > 运行前，输入 
> > > `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E`
> > > 然后再次运行脚本就可以了
> > 
> > 
> > 好的，谢谢大佬，手动抱拳
> 
> 没事，不用谢

老哥，所以在线编辑工具之后需不需要更新？是自动更新还是手动更新？

**Comment by lan-tianxiang** [comment]
还是得通过对比工具自己手动更新的
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, May 28, 2021 09:47 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [lan-tianxiang/JS_TOOL] 能说明下如何设置cookie吗？用的安卓 (#26)

&nbsp;



     
这又是啥情况啊，老哥？1 debian/ubuntu/armbian/OpenMediaVault，以及其他debian系
 点击数：1 http://mirrors.ustc.edu.cn/debian 稳定版
 点击数：2 http://mirrors.ustc.edu.cn/debian stable-updates发布
 获取：3 https://dl.yarnpkg.com/debian 稳定的InRelease [17.1 kB]
 错误：3 https://dl.yarnpkg.com/debian stable InRelease
 由于公共密钥不可用，因此无法验证以下签名：NO_PUBKEY 23E7166788B63E1E
 正在阅读包裹清单...完成
 W：GPG错误： ： https //dl.yarnpkg.com/debian稳定InRelease：由于公共密钥不可用，无法验证以下签名：NO_PUBKEY 23E7166788B63E1E
 E：存储库“ https://dl.yarnpkg.com/debian stable InRelease”未签名。
 N：无法安全地从这样的存储库更新，因此默认情况下被禁用。
 N：有关存储库创建和用户配置的详细信息，请参见apt-secure（8）联机帮助页。
 依赖未安装完整,请重新运行该脚本且切换良好的网络环境！
  
@895450603
 运行前，输入
 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E
 然后再次运行脚本就可以了
  
好的，谢谢大佬，手动抱拳
  
没事，不用谢
  
老哥，所以在线编辑工具之后需不需要更新？是自动更新还是手动更新？

**Comment by ghost** [comment]
![IMG_20210609_052628](https://user-images.githubusercontent.com/85585173/121259957-4d016300-c8e3-11eb-96ba-9fe61da09282.jpg)
大佬，这个怎么解决，我进不去控制面板

**Comment by lan-tianxiang** [comment]
cd jd
bash jd.sh panelon

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："AM639 ***@***.***&gt;;
发送时间：2021年6月9日(星期三) 凌晨5:27
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 能说明下如何设置cookie吗？用的安卓 (#26)
-----------------------------------

 

 

 大佬，这个怎么解决，我进不去控制面板

**Comment by ghost** [comment]
> cd jd bash jd.sh 面板
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："AM639 ***@***.***&gt;; 发送时间：2021年6月9日(星期三) 凌晨5:27 收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;; 抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 能说明下如何设置cookie吗？用的安卓 (#26) ----------------------------------- 大佬，这个怎么解决，我进不去控制面板 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

只能一个个运行嘛不能一次运行全部嘛

**Comment by better319** [comment]
A1版本   服务器运行的话，应该怎么设置让他再后台自己运行。![Uploading image.png…]()

**Comment by better319** [comment]
![Uploading image.png…]()

**Comment by better319** [comment]
jd runall2
显示命令输入错误 A1版本

**Comment by lan-tianxiang** [comment]
@better319   部署完之后就不用管，填写完账号就会自动运行

**Comment by lan-tianxiang** [comment]
@better319  输入bash jd.sh runall2

**Comment by better319** [comment]
我是在浏览器那个界面操作的。。

**Comment by better319** [comment]
![Uploading image.png…]()

**Comment by better319** [comment]
我还有个问题，如果我只有一个手机，用的termux，我进入到浏览器的扫码界面后，我怎么操作？扫码啊，，就一个手机，截屏？？好像没用啊，然后这个cookie的数据也不会自动填写啊？纠结。

**Comment by lan-tianxiang** [comment]
> 我还有个问题，如果我只有一个手机，用的termux，我进入到浏览器的扫码界面后，我怎么操作？扫码啊，，就一个手机，截屏？？好像没用啊，然后这个cookie的数据也不会自动填写啊？纠结。

@better319 控制面板内的扫码的确不会自动填写，目前只有首页的才行

**Comment by better319** [comment]
没找到首页，我主要是忘记怎么获取cookie了。。。这个能在说下嘛？最好是电脑端
