### ISSUE TITLE
京喜工厂拼团瓜分电力活动团ID（activeId）已失效

### ISSUE THREAD

**Issue by Rosylusi** [lan-tianxiang/JS_TOOL#31]
京喜工厂拼团瓜分电力活动团ID（activeId）已失效
请自行抓包替换(Node环境变量为TUAN_ACTIVEID，iOS端在BoxJx)或者联系作者等待更新
如何解决？

**Comment by lan-tianxiang** [comment]
更新一下，用对比工具修改一下配置文件

**Comment by Rosylusi** [comment]
> 
> 
> 更新一下，用对比工具修改一下配置文件

已经注释了，但好像还是会提醒
![微信截图_20210531140328](https://user-images.githubusercontent.com/43165837/120147300-0643a700-c219-11eb-9f69-96b019525dd9.png)
![微信截图_20210531140257](https://user-images.githubusercontent.com/43165837/120147307-080d6a80-c219-11eb-9244-734376ee402d.png)

**Comment by lan-tianxiang** [comment]
嗯，脚本的问题😂 ，等下修复

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："easonren ***@***.***&gt;;
发送时间：2021年5月31日(星期一) 下午2:04
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 京喜工厂拼团瓜分电力活动团ID（activeId）已失效 (#31)
-----------------------------------

 

  
更新一下，用对比工具修改一下配置文件
  
已经注释了，但好像还是会提醒

**Comment by Rosylusi** [comment]
> 
> 嗯，脚本的问题 😂 ，等下修复
> [… ](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："easonren ***@***.***>; 发送时间：2021年5月31日(星期一) 下午2:04 收件人："lan-tianxiang/JS_TOOL" ***@***.***>; 抄送："lan-tianxiang ***@***.***>;"Comment ***@***.***>; 主题：Re: [lan-tianxiang/JS_TOOL] 京喜工厂拼团瓜分电力活动团ID（activeId）已失效 ( [#31 ](https://github.com/lan-tianxiang/JS_TOOL/issues/31)) ----------------------------------- 更新一下，用对比工具修改一下配置文件 已经注释了，但好像还是会提醒 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

给大佬倒茶

**Comment by lan-tianxiang** [comment]
好了

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："easonren ***@***.***&gt;;
发送时间：2021年5月31日(星期一) 下午2:09
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 京喜工厂拼团瓜分电力活动团ID（activeId）已失效 (#31)
-----------------------------------

 

  
嗯，脚本的问题  ，等下修复
 … 
 ---------- 该邮件从移动设备发送
 --------------原始邮件-------------- 发件人："easonren @.&gt;; 发送时间：2021年5月31日(星期一) 下午2:04 收件人："lan-tianxiang/JS_TOOL" @.&gt;; 抄送："lan-tianxiang @.&gt;;"Comment @.&gt;; 主题：Re: [lan-tianxiang/JS_TOOL] 京喜工厂拼团瓜分电力活动团ID（activeId）已失效 ( #31 ) ----------------------------------- 更新一下，用对比工具修改一下配置文件 已经注释了，但好像还是会提醒 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
给大佬倒茶

**Comment by JasminesTang** [comment]
👍

**Comment by Rosylusi** [comment]
老哥你好，首先感谢你的无私奉献和指导，让我从一个完全小白变成可以自己搭建的略懂者，我现在环境已经OK，电脑虚拟机也可以正常运行，但是我用手机运行linux deploy之后可以正常进入面板，但是定时任务完全不会运行，这是什么原因？是手机后台杀掉了吗？我也已经锁定了任务后台！

发自我的iPhone

**Comment by lan-tianxiang** [comment]
哈哈，不用谢，很高兴帮到你🥰，回归正题
linux deploy和 win10 ubuntu类似都要自己启动cron服务才行的

**Comment by Rosylusi** [comment]
crond -ipP
请问是这段代码吗？

发自我的iPhone

**Comment by Rosylusi** [comment]
> 
> 
> 哈哈，不用谢，很高兴帮到你🥰，回归正题
> linux deploy和 win10 ubuntu类似都要自己启动cron服务才行的

我按照viki当中的代码，提示
root@localhost:~/jd/panel# crond -ipP
bash: crond: command not found
请问该如何解决？
![微信截图_20210601123307](https://user-images.githubusercontent.com/43165837/120267031-b545b880-c2d5-11eb-9489-4a40ba7c835a.png)

**Comment by lan-tianxiang** [comment]
@895450603   试试
`service cron start`

**Comment by Rosylusi** [comment]
> @895450603 试试
> `service cron start`

root@localhost:~/jd/panel# service cron start
[ ok ] Starting periodic command scheduler: cron.
这样然后配置上cookie就可以吗？

**Comment by lan-tianxiang** [comment]
是的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："easonren ***@***.***&gt;;
发送时间：2021年6月1日(星期二) 中午1:46
收件人："lan-tianxiang/JS_TOOL" ***@***.***&gt;;
抄送："lan-tianxiang ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [lan-tianxiang/JS_TOOL] 京喜工厂拼团瓜分电力活动团ID（activeId）已失效 (#31)
-----------------------------------

 

  
@895450603 试试
 service cron start
  
***@***.***:~/jd/panel# service cron start
 [ ok ] Starting periodic command scheduler: cron.
 这样然后配置上cookie就可以吗？
